spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/athletixactivity
      database: athletixactivity
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8082

eureka:
  client:
    defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: athletix.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking