spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/athletixactivity
      database: athletixactivity


server:
  port: 8082

eureka:
  client:
    defaultZone: http://localhost:8761/eureka/